// <auto-generated />
using System;
using CraftShopAPI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CraftShopAPI.Migrations
{
    [DbContext(typeof(CraftShopDbContext))]
    [Migration("20260101153821_CraftShopDB")]
    partial class CraftShopDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("CraftShopAPI.Domain.Entities.BaseProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("TEXT");

                    b.HasKey("ProductId");

                    b.ToTable("BaseProduct");

                    b.HasDiscriminator<string>("Discriminator").HasValue("BaseProduct");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("CraftShopAPI.Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("InvoiceId");

                    b.HasIndex("OrderId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("CraftShopAPI.Domain.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductsId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CraftShopAPI.Domain.Entities.Chair", b =>
                {
                    b.HasBaseType("CraftShopAPI.Domain.Entities.BaseProduct");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasCushion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfLegs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasDiscriminator().HasValue("Chair");
                });

            modelBuilder.Entity("CraftShopAPI.Domain.Entities.CrystalDecor", b =>
                {
                    b.HasBaseType("CraftShopAPI.Domain.Entities.BaseProduct");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CrystalType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHandcrafted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("BaseProduct", t =>
                        {
                            t.Property("Color")
                                .HasColumnName("CrystalDecor_Color");

                            t.Property("Name")
                                .HasColumnName("CrystalDecor_Name");
                        });

                    b.HasDiscriminator().HasValue("CrystalDecor");
                });

            modelBuilder.Entity("CraftShopAPI.Domain.Entities.Lamp", b =>
                {
                    b.HasBaseType("CraftShopAPI.Domain.Entities.BaseProduct");

                    b.Property<string>("BulbType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasDimmer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShadeShape")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("BaseProduct", t =>
                        {
                            t.Property("Color")
                                .HasColumnName("Lamp_Color");

                            t.Property("Material")
                                .HasColumnName("Lamp_Material");

                            t.Property("Name")
                                .HasColumnName("Lamp_Name");
                        });

                    b.HasDiscriminator().HasValue("Lamp");
                });

            modelBuilder.Entity("CraftShopAPI.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("CraftShopAPI.Domain.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
