// <auto-generated />
using System;
using CraftShopAPI.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CraftShopAPI.Migrations
{
    [DbContext(typeof(CraftShopDbContext))]
    partial class CraftShopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.2");

            modelBuilder.Entity("CraftShopAPI.Domain.Entities.BaseProduct", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("ProductId");

                    b.ToTable("BaseProduct");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("CraftShopAPI.Domain.Entities.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("BillingAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("InvoiceId");

                    b.HasIndex("OrderId");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("CraftShopAPI.Domain.Entities.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProductsId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShippingAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("CraftShopAPI.Domain.Entities.Chair", b =>
                {
                    b.HasBaseType("CraftShopAPI.Domain.Entities.BaseProduct");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasCushion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NumberOfLegs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Chair", (string)null);
                });

            modelBuilder.Entity("CraftShopAPI.Domain.Entities.CrystalDecor", b =>
                {
                    b.HasBaseType("CraftShopAPI.Domain.Entities.BaseProduct");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CrystalType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsHandcrafted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Shape")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("CrystalDecor", (string)null);
                });

            modelBuilder.Entity("CraftShopAPI.Domain.Entities.Lamp", b =>
                {
                    b.HasBaseType("CraftShopAPI.Domain.Entities.BaseProduct");

                    b.Property<string>("BulbType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("HasDimmer")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ShadeShape")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.ToTable("Lamp", (string)null);
                });

            modelBuilder.Entity("CraftShopAPI.Domain.Entities.Invoice", b =>
                {
                    b.HasOne("CraftShopAPI.Domain.Entities.Order", null)
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CraftShopAPI.Domain.Entities.Chair", b =>
                {
                    b.HasOne("CraftShopAPI.Domain.Entities.BaseProduct", null)
                        .WithOne()
                        .HasForeignKey("CraftShopAPI.Domain.Entities.Chair", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CraftShopAPI.Domain.Entities.CrystalDecor", b =>
                {
                    b.HasOne("CraftShopAPI.Domain.Entities.BaseProduct", null)
                        .WithOne()
                        .HasForeignKey("CraftShopAPI.Domain.Entities.CrystalDecor", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CraftShopAPI.Domain.Entities.Lamp", b =>
                {
                    b.HasOne("CraftShopAPI.Domain.Entities.BaseProduct", null)
                        .WithOne()
                        .HasForeignKey("CraftShopAPI.Domain.Entities.Lamp", "ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
